apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  env.js: |
    window.env = {
      VITE_SUPABASE_URL=https://wapqwpuvkskskdxpdeem.supabase.co,
      VITE_SUPABASE_ANON_KEY=sb_publishable_wCyRVgvYfHsRHtB66iwRgg_4G11jwVw,
      VITE_API_URL=http://localhost:5000
    };


