apiVersion: apps/v1
kind: Deployment
metadata:
  name: dengueguard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dengueguard-backend
  template:
    metadata:
      labels:
        app: dengueguard-backend
    spec:
      containers:
        - name: dengue-backend
          image: thimansa/dengueguard-backend:latest
          env:
          - name: SUPABASE_URL
            valueFrom:
              configMapKeyRef:
                name: supabase-config
                key: SUPABASE_URL

          - name: SUPABASE_ANON_KEY
            valueFrom:
              secretKeyRef:
                name: supabase-secret
                key: SUPABASE_ANON_KEY
          ports:
            - containerPort: 5000