export const mohAreas = [
  "MOH-Akurana", "MOH-Bambaradeniya", "MOH-Doluwa", "MOH-Galagedara", "MOH-Galaha",
  "MOH-Gampola (Udapalatha)", "MOH-Gangawata Korale", "MOH-Hasalaka", "MOH-Hatharaliyadda",
  "MOH-Kandy MC", "MOH-Kundasale", "MOH-Kurunduwaththa (Gangaihala)", 
  "MOH-Medadumbara (Meda Mahanuwara)", "MOH-Menikhinna", "MOH-Panvila", 
  "MOH-Pasbage (Nawalapitiya)", "MOH-Poojapitiya", "MOH-Thalathuoya - Pathahewaheta", 
  "MOH-Udadumbara", "MOH-Udunuwara", "MOH-Waththegama (Pathadumbara)", 
  "MOH-Werellagama (Harispattuwa)", "MOH-Yatinuwara (Kadugannawa)", "MOH-Ambanganga Korale", 
  "MOH-Dambulla", "MOH-Dambulla MC", "MOH-Galewela", "MOH-Laggala", "MOH-Matale", 
  "MOH-Matale MC", "MOH-Naula", "MOH-Pallepola", "MOH-Rattota", "MOH-Ukuwela", 
  "MOH-Wilgamuwa", "MOH-Yatawatta", "MOH-Ambagamuwa(Ginigath Hena)", "MOH-Bogawanthalawa", 
  "MOH-Kotagala", "MOH-Kothmale", "MOH-Lindula(Thalawakale)", "MOH-Maskeliya", 
  "MOH-Mathurata", "MOH-Nawathispane", "MOH-Nuwara Eliya", "MOH-Nuwara Eliya MC", 
  "MOH-Ragala", "MOH-Rikillagaskada (Hanguranketha)", "MOH-Walapane", "MOH-Ampara", 
  "MOH-Damana", "MOH-Dehiattakandiya", "MOH-Lahugala", "MOH-Mahaoya", "MOH-Padiyatalawa", 
  "MOH-Uhana", "MOH-Arayampathy", "MOH-Batticoloa", "MOH-Chenkalady", "MOH-Eravur", 
  "MOH-Kaluwanchikudy", "MOH-Kathankudy", "MOH-Kiran", "MOH-Koralai Pattu Central", 
  "MOH-Oddamavady", "MOH-Paddipalai", "MOH-Vakarai", "MOH-Valaichchenai", "MOH-Vavunathevu", 
  "MOH-Vellavely", "MOH-Addalachchenai", "MOH-Akkaraipathu", "MOH-Alayadivembu", 
  "MOH-Irakkamam", "MOH-Kalmunai North", "MOH-Kalmunai South", "MOH-Karaithivu", 
  "MOH-Navithanveli", "MOH-Ninthavur", "MOH-Pottuvil", "MOH-Sainthamaruthu", 
  "MOH-Sammanthurai", "MOH-Thirukkovil", "MOH-Echchalampattu", "MOH-Gomarangadawela", 
  "MOH-Kanthale", "MOH-Kinniya", "MOH-Kuchchavelly", "MOH-Kuriucharkerny", "MOH-Muthur", 
  "MOH-Padavisripura", "MOH-Seruwila", "MOH-Thampalakamam", "MOH-Trincomalee", 
  "MOH-Uppuveli", "MOH-Anuradhapura MC", "MOH-Galenbindunuwewa", "MOH-Galkiriyagama (Palagala)", 
  "MOH-Galnewa", "MOH-Horowpothana", "MOH-Ipalogama", "MOH-Kahatagasdigiliya", 
  "MOH-Kebithigollewa", "MOH-Kekirawa", "MOH-Maha Wilachchiya", "MOH-Medawachchiya", 
  "MOH-Mihinthale", "MOH-Nachchaduwa", "MOH-Nochchiyagama", "MOH-Nuwaragam-Palatha-Central", 
  "MOH-Nuwaragam-Palatha-East", "MOH-Padaviya", "MOH-Palugaswewa", "MOH-Rajanganaya", 
  "MOH-Rambewa", "MOH-Thalawa", "MOH-Thambuttegama", "MOH-Thirappane", "MOH-Wilachchiya", 
  "MOH-Aralaganwila", "MOH-Bakamuna (Elahera)", "MOH-Hingurakgoda", "MOH-Lankapura", 
  "MOH-Medirigiriya", "MOH-Siripura", "MOH-Thamankaduwa", "MOH-Welikanda", "MOH-Alawwa", 
  "MOH-Ambanpola", "MOH-Bamunakotuwa", "MOH-Bingiriya", "MOH-Ehetuwewa", "MOH-Galgamuwa", 
  "MOH-Ganewatta", "MOH-Giribawa", "MOH-Ibbagamuwa (Gokarella)", "MOH-Katupotha (Kuliyapitiya East)", 
  "MOH-Kobeigane", "MOH-Kotawehera", "MOH-Kuliyapitiya", "MOH-Kurunegala", "MOH-Maho", 
  "MOH-Mallawapitiya", "MOH-Mawathagama", "MOH-MC Kurunegala", "MOH-Narammala", 
  "MOH-Nikaweratiya", "MOH-panduwasnuwara East", "MOH-Panduwasnuwara West", "MOH-Pannala", 
  "MOH-Polgahawela", "MOH-Polpithigama", "MOH-Rasnayakapura", "MOH-Rideegama", 
  "MOH-Udubaddawa", "MOH-Wariyapola", "MOH-Weerambugedara", "MOH-Anamaduwa", 
  "MOH-Arachchikattuwa", "MOH-Chilaw", "MOH-Dankotuwa", "MOH-Kalpitiya", "MOH-Karuwalagaswewa", 
  "MOH-Madampe", "MOH-Mahawewa", "MOH-Mundel", "MOH-Munel", "MOH-Nattandiya", 
  "MOH-Pallama", "MOH-Puttalam", "MOH-Wennappuwa", "MOH-Chankanai Walikamam West", 
  "MOH-Chavakachchari", "MOH-Jaffna", "MOH-Karainagar", "MOH-Karaveddy", "MOH-Kayts", 
  "MOH-Kopay", "MOH-Maruthankerny", "MOH-Nallur", "MOH-Point Pedro", "MOH-Sandilipay", 
  "MOH-Telippalai", "MOH-Uduvil", "MOH-Velani", "MOH-Kandawala", "MOH-Karachchi/Kilinochchci", 
  "MOH-Pallai", "MOH-Poonakery", "MOH-Madhu", "MOH-Mannar Town", "MOH-Manthalai West", 
  "MOH-Musali", "MOH-Nanattan", "MOH-Mallavi", "MOH-Manthai East", "MOH-Mullaitivu", 
  "MOH-Oddusudan", "MOH-Puthukkudiyituppu", "MOH-Thunnukai", "MOH-Welioya", "MOH-Cheddikulam", 
  "MOH-Vavuniya", "MOH-Vavuniya North", "MOH-Vavuniya South", "MOH-Aranayaka", 
  "MOH-Bulathkohupitiya", "MOH-Dehiovita", "MOH-Deraniyagala", "MOH-Galigamuwa", 
  "MOH-Kegalle", "MOH-Mawanella", "MOH-Rambukkana", "MOH-Ruwanwella", "MOH-Warakapola", 
  "MOH-Yatiyanthota", "MOH-Ayagama", "MOH-Balangoda", "MOH-Eheliyagoda", "MOH-Elapatha", 
  "MOH-Embilipitiya", "MOH-Godakawela", "MOH-Imbulpe", "MOH-Kahawatta", "MOH-Kalawana", 
  "MOH-Kalthota", "MOH-Kiriella", "MOH-Kolonna", "MOH-Kuruvita", "MOH-Nivithigala", 
  "MOH-Openayaka", "MOH-Pelmadulla", "MOH-Rathnapura MC", "MOH-Ratnapura PS", "MOH-Udawalwa", 
  "MOH-Weligepola", "MOH-Akmeemana", "MOH-Ambalangoda", "MOH-Baddegama", "MOH-Balapitiya", 
  "MOH-Bope Poddala", "MOH-Elpitiya", "MOH-Gonapinuwala", "MOH-Habaraduwa", "MOH-Hikkaduwa", 
  "MOH-Imaduwa", "MOH-Induruwa", "MOH-Karandeniya", "MOH-MC Galle", "MOH-Neluwa", 
  "MOH-Niyagama", "MOH-Rathgama", "MOH-Thawalama", "MOH-Udugama", "MOH-Walivitiya (Divithura)", 
  "MOH-Yakkalamulla", "MOH-Ambalantota", "MOH-Angunukolapelessa", "MOH-Beliatta", 
  "MOH-Hambantota", "MOH-Katuwana", "MOH-Lunugamwehera", "MOH-Okewela", "MOH-Sooriyawewa", 
  "MOH-Tangalle", "MOH-Tissamaharama", "MOH-Walasmulla", "MOH-Weeraketiya", "MOH-Akuressa", 
  "MOH-Athuraliya", "MOH-Deniyaya/Kotapola", "MOH-Devinuwara", "MOH-Dickwella", "MOH-Hakmana", 
  "MOH-Kamburupitiya", "MOH-Kirinda-Puhulwella", "MOH-Malimbada", "MOH-Matara MC", 
  "MOH-Matara PS Kekanadura", "MOH-Morawaka", "MOH-Mulatiyana", "MOH-Pasgoda/Urubokka", 
  "MOH-Thihagoda", "MOH-Weligama", "MOH-Welipitiya", "MOH-Badulla", "MOH-Bandarawela", 
  "MOH-Ella", "MOH-Girandurukotte", "MOH-Haldummulla", "MOH-Hali Ela", "MOH-Haputale", 
  "MOH-Kandaketiya", "MOH-Lunugala", "MOH-Mahiyanganaya", "MOH-Meegahakivula", "MOH-Passara", 
  "MOH-Rideemaliyadda", "MOH-Soranathota", "MOH-Uva Paranagama", "MOH-Welimada", 
  "MOH-Badalkumbura", "MOH-Bibile", "MOH-Buttala", "MOH-Kataragama", "MOH-Madulla", 
  "MOH-Medagama", "MOH-Monaragala", "MOH-Sevanagala", "MOH-Siyambalanduwa", "MOH-Thanamalwila", 
  "MOH-Wellawaya", "MOH-D1-CMC", "MOH-D2A-CMC", "MOH-D2B-CMC", "MOH-D3-CMC", "MOH-D4-CMC", 
  "MOH-D5-CMC", "PORT - HEALTH OFFICE (D1 CMC)", "MOH-Battaramulla", "MOH-Boralesgamuwa", 
  "MOH-Dehiwala", "MOH-Egodauyana", "MOH-Gothatuwa", "MOH-Hanwella", "MOH-Homagama", 
  "MOH-Kaduwela", "MOH-Kahathuduwa (Wethara)", "MOH-Kesbewa", "MOH-Kolonnawa", 
  "MOH-Maharagama", "MOH-Moratuwa", "MOH-Nugegoda", "MOH-Padukka", "MOH-Piliyandala", 
  "MOH-Pitakotte (Kotte)", "MOH-Port City", "MOH-Rathmalana", "MOH-Aththanagalla", 
  "MOH-Biyagama", "MOH-Divulapitiya", "MOH-Gampaha", "MOH-Ja-Ela", "MOH-Katana", 
  "MOH-Kelaniya", "MOH-Mahara", "MOH-Meerigama", "MOH-Minuwangoda", "MOH-Negombo", 
  "MOH-Pugoda (Dompe)", "MOH-Ragama", "MOH-Seeduwa", "MOH-Wattala", "MOH-Agalawatta", 
  "MOH-Bandaragama", "MOH-Bulathsinhala", "MOH-Dodangoda PS", "MOH-Horana", "MOH-Ingiriya", 
  "MOH-Madurawala", "MOH-Mathugama", "MOH-Millaniya", "MOH-Palindanuwara", "MOH-Panadura", 
  "MOH-Wadduwa", "MOH-Walallawita", "MOH-Aluthgama", "MOH-Beruwala", "MOH-Kalutara", 
  "MOH-Payagala"
];